#!/usr/bin/env python3
"""Trim vendored yt-dlp into a Chaquopy-friendly package tree.

Generates lazy_extractors.py, copies yt_dlp/, drops CLI-only / non-Android pieces.
"""
from __future__ import annotations

import argparse
import ast
import shutil
import subprocess
import sys
from pathlib import Path

DROP_FILES = {
    "yt_dlp/__main__.py",
    # Keep options.py: package __init__ imports parseOpts at load time.
    # Keep update.py: YoutubeDL/options import several symbols from it.
}
DROP_DIRS = {
    "yt_dlp/__pyinstaller",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--src",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "third_party" / "yt-dlp",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output directory that will contain yt_dlp/ (e.g. build/generated/ytdlp)",
    )
    args = parser.parse_args()

    src: Path = args.src
    out: Path = args.out
    if not (src / "yt_dlp").is_dir():
        print(f"error: yt-dlp package not found at {src / 'yt_dlp'}", file=sys.stderr)
        return 1

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    # Generate lazy extractors in the source tree (idempotent enough for CI).
    lazy_script = src / "devscripts" / "make_lazy_extractors.py"
    lazy_out = src / "yt_dlp" / "extractor" / "lazy_extractors.py"
    if lazy_script.is_file():
        subprocess.check_call([sys.executable, str(lazy_script), str(lazy_out)], cwd=src)

    dest_pkg = out / "yt_dlp"
    shutil.copytree(
        src / "yt_dlp",
        dest_pkg,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".mypy_cache"),
    )

    for rel in DROP_FILES:
        path = out / rel
        if path.exists():
            path.unlink()

    for rel in DROP_DIRS:
        path = out / rel
        if path.is_dir():
            shutil.rmtree(path)

    # external.py shells out to aria2c/curl/wget/ffmpeg — unusable in the app sandbox.
    external = dest_pkg / "downloader" / "external.py"
    if external.exists():
        external.write_text(build_external_stub(external.read_text()))

    print(f"Wrote trimmed yt-dlp to {out}")
    return 0


# Names whose behaviour the stub has to get right rather than merely provide.
_EXPLICIT_FUNCS = {
    "list_external_downloaders": "    return []\n",
    "get_external_downloader": "    return None\n",
}

_STUB_HEADER = '''"""Stub: external downloaders are not available on Android.

Generated by tools/trim_ytdlp.py from the upstream module's public surface, so a new
external downloader class in yt-dlp cannot turn into an ImportError on a user's device.
"""
from ..utils import DownloadError


class ExternalFD:
    EXE_NAME = 'external'
    SUPPORTED_PROTOCOLS = ()
    SUPPORTED_FEATURES = ()

    def __init__(self, ydl, params):
        self.ydl = ydl
        self.params = params

    @classmethod
    def get_basename(cls):
        return cls.__name__[:-2].lower()

    @classmethod
    def available(cls, path=None):
        return False

    @classmethod
    def supports(cls, info_dict):
        return False

    @classmethod
    def can_download(cls, info_dict, path=None):
        return False

    @classmethod
    def can_merge_formats(cls, info_dict, params):
        return False

    def real_download(self, filename, info_dict):
        raise DownloadError(
            f'{self.get_basename()} is not available on Android; '
            'use a progressive/native format instead'
        )


class FFmpegFD(ExternalFD):
    EXE_NAME = 'ffmpeg'
    SUPPORTED_PROTOCOLS = (
        'http', 'https', 'ftp', 'ftps', 'm3u8', 'm3u8_native',
        'rtsp', 'rtmp', 'rtmp_ffmpeg', 'mms', 'http_dash_segments',
    )
'''


def build_external_stub(original_source: str) -> str:
    """Mirror every public name upstream's external.py exports, reporting unavailable.

    Hand-writing the stub meant that whenever yt-dlp added a symbol imported elsewhere
    in the package, the build still succeeded and the failure only showed up as an
    AttributeError at runtime on a device.
    """
    tree = ast.parse(original_source)
    classes: list[str] = []
    functions: list[str] = []
    aliases: list[tuple[str, str]] = []
    constants: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                functions.append(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if not isinstance(target, ast.Name) or target.id.startswith("_"):
                    continue
                # Upstream sometimes exposes an alias, e.g. AVconvFD = FFmpegFD.
                # Emitting None for those would break `issubclass` checks downstream.
                if isinstance(node.value, ast.Name):
                    aliases.append((target.id, node.value.id))
                else:
                    constants.append(target.id)

    parts = [_STUB_HEADER]

    for name in classes:
        if name in ("ExternalFD", "FFmpegFD"):
            continue
        exe = name[:-2].lower() if name.endswith("FD") else name.lower()
        parts.append(
            f"\n\nclass {name}(ExternalFD):\n    EXE_NAME = {exe!r}\n"
        )

    for alias, target in aliases:
        if target in classes or target in ("ExternalFD", "FFmpegFD"):
            parts.append(f"\n\n{alias} = {target}\n")
        else:
            constants.append(alias)

    for name in functions:
        body = _EXPLICIT_FUNCS.get(name, "    return None\n")
        parts.append(f"\n\ndef {name}(*args, **kwargs):\n{body}")

    for name in constants:
        parts.append(f"\n\n{name} = None\n")

    missing = [n for n in _EXPLICIT_FUNCS if n not in functions]
    if missing:
        raise SystemExit(
            f"error: upstream external.py no longer defines {missing}; "
            "update tools/trim_ytdlp.py — the Android stub would break at runtime"
        )

    return "".join(parts)


if __name__ == "__main__":
    raise SystemExit(main())
